# PhoBERT -- Combined augmentation (BT + EDA + LLM)

Train trên subset `combined_segmented` (đã phân từ sẵn trên Hugging Face Hub), đánh giá trên `tdtu_dev` / `tdtu_test` (đã đóng băng).

**Chạy trên Google Colab** -- cần mount Drive và có sẵn secret `HF_TOKEN` (biểu tượng chìa khoá bên trái > Add new secret).

## Dependencies

In [ ]:
!pip install -q transformers datasets huggingface_hub scikit-learn accelerate sentencepiece
!pip install -q -U datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 10.7 MB/s eta 0:00:00

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Warning: Enable GPU in Runtime > Change runtime type.")

Device: cuda
GPU: Tesla T4

In [ ]:
from google.colab import userdata
from huggingface_hub import login, whoami, HfApi

hf_token = userdata.get("HF_TOKEN")
login(token=hf_token, add_to_git_credential=False)
user_info = whoami()
print(f"Authenticated as: {user_info['name']}")

Authenticated as: AnoraLee

In [ ]:
from google.colab import drive
from pathlib import Path

drive.mount("/content/drive")

PROJECT_DIR = Path("/content/drive/MyDrive/Hate_Speech_Detection")
MODELS_DIR = PROJECT_DIR / "models"
RESULTS_DIR = PROJECT_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project root: {PROJECT_DIR}")

Mounted at /content/drive
Project root: /content/drive/MyDrive/Hate_Speech_Detection

In [ ]:
MODEL_NAME = "vinai/phobert-base"
MAX_LENGTH = 128
SEED = 42
LABELS = ["CLEAN", "OFFENSIVE", "HATE"]

label2id = {label: index for index, label in enumerate(LABELS)}
id2label = {index: label for label, index in label2id.items()}

# Repo data trên Hugging Face Hub
HF_DATA_REPO = "AnoraLee/tdtu_vietnamese_hsd_final"
# Subset cho notebook combined
SUBSET_NAME = "combined_segmented"

## Load dữ liệu đã phân từ sẵn từ Hugging Face Hub

Data trên Hub đã được xử lý sạch (chuẩn hoá teencode + phân từ VnCoreNLP + gộp 5 nguồn baseline/BT/EDA/LLM, loại conflict + leakage với dev/test) nên **không cần chạy lại segmentation**.

In [ ]:
from datasets import load_dataset
import pandas as pd

REPO_DATA = "AnoraLee/tdtu_vietnamese_hsd_final"

print("Đang tải tập Train [combined_segmented] từ Hugging Face...")
dataset_train = load_dataset(REPO_DATA, "combined_segmented")
train_df = dataset_train["tdtu_train"].to_pandas()

print("Đang tải tập Dev/Test [baseline_segmented] từ Hugging Face...")
# Kéo tập dev và test từ baseline gốc (frozen splits)
dataset_eval = load_dataset(REPO_DATA, "baseline_segmented")
dev_df = dataset_eval["tdtu_dev"].to_pandas()
test_df = dataset_eval["tdtu_test"].to_pandas()

# ⚠️ QUAN TRỌNG VỚI PHO-BERT: Chỉ dùng cột 'text' (đã phân từ sẵn với dấu gạch dưới)
# Nếu bạn đang chạy ViSoBERT thì nhớ đổi thành train_df["text"] = train_df["text_raw"] ở bước này
train_df = train_df.dropna(subset=["text", "label"]).reset_index(drop=True)
dev_df = dev_df.dropna(subset=["text", "label"]).reset_index(drop=True)
test_df = test_df.dropna(subset=["text", "label"]).reset_index(drop=True)

print(f"Kích thước Train: {train_df.shape}")
print(f"Kích thước Dev: {dev_df.shape}")
print(f"Kích thước Test: {test_df.shape}")

Đang tải tập Train [combined_segmented] từ Hugging Face...
Đang tải tập Dev/Test [baseline_segmented] từ Hugging Face...

baseline_segmented/tdtu_train-00000-of-0(…): reconstructing file:   0%|          |  0.00B / 8.69MB

baseline_segmented/tdtu_train-00000-of-0(…): downloading bytes:           |  0.00B

baseline_segmented/tdtu_dev-00000-of-000(…): reconstructing file:   0%|          |  0.00B /  127kB

baseline_segmented/tdtu_dev-00000-of-000(…): downloading bytes:           |  0.00B

baseline_segmented/tdtu_test-00000-of-00(…): reconstructing file:   0%|          |  0.00B /  314kB

baseline_segmented/tdtu_test-00000-of-00(…): downloading bytes:           |  0.00B

Generating tdtu_train split:   0%|          | 0/86719 [00:00<?, ? examples/s]

Generating tdtu_dev split:   0%|          | 0/2650 [00:00<?, ? examples/s]

Generating tdtu_test split:   0%|          | 0/6576 [00:00<?, ? examples/s]

Kích thước Train: (140914, 4)
Kích thước Dev: (2650, 2)
Kích thước Test: (6576, 2)

## Tokenizer + hàm dùng chung

In [ ]:
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )

def prepare_split(df):
    output = df[["text", "label"]].dropna().copy()
    assert output["label"].isin(LABELS).all(), "Unexpected label found."
    output["label"] = output["label"].map(label2id)
    return Dataset.from_pandas(output, preserve_index=False)

def build_tokenized_dataset(train_df, dev_df, test_df):
    dataset = DatasetDict({
        "train": prepare_split(train_df),
        "validation": prepare_split(dev_df),
        "test": prepare_split(test_df),
    })
    tokenized = dataset.map(tokenize_function, batched=True)
    tokenized = tokenized.rename_column("label", "labels")
    model_columns = [
        c for c in ["input_ids", "attention_mask", "token_type_ids", "labels"]
        if c in tokenized["train"].column_names
    ]
    tokenized.set_format("torch", columns=model_columns)
    print(tokenized)
    return tokenized

config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.13M [00:00<?, ?B/s]

In [ ]:
tokenized = build_tokenized_dataset(train_df, dev_df, test_df)

Map:   0%|          | 0/140914 [00:00<?, ? examples/s]

Map:   0%|          | 0/2650 [00:00<?, ? examples/s]

Map:   0%|          | 0/6576 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 140914
    })
    validation: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 2650
    })
    test: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 6576
    })
})

## Metrics

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    """Unified metric schema -- MUST stay identical across all 3 notebooks
    so results in the report are directly comparable."""
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro"),
        "weighted_f1": f1_score(labels, predictions, average="weighted"),
        "hate_f1": f1_score(labels, predictions, labels=[LABELS.index("HATE")], average="macro"),
    }

## Train

In [ ]:
import json
from transformers import TrainingArguments, AutoModelForSequenceClassification, Trainer, set_seed, EarlyStoppingCallback

set_seed(SEED)

def train_experiment(experiment_name, model_dir_name, tokenized, push_to_hub_repo=None):
    """Load a FRESH PhoBERT model and train one experiment end to end.
    Always instantiates a new model -- never reuses a model/trainer object
    from a previous cell, to avoid accidental weight leakage between runs."""
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=3, label2id=label2id, id2label=id2label,
    )
    model_dir = MODELS_DIR / model_dir_name

    training_args = TrainingArguments(
        output_dir=str(model_dir / "_checkpoints"),
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=10,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        fp16=torch.cuda.is_available(),
        logging_steps=50,
        report_to="none",
        save_total_limit=1,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized["train"],
        eval_dataset=tokenized["validation"],
        processing_class=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    trainer.train()

    test_metrics = trainer.evaluate(tokenized["test"], metric_key_prefix="test")
    print(f"[{experiment_name}] test metrics: {test_metrics}")

    trainer.save_model(model_dir)
    tokenizer.save_pretrained(model_dir)

    metrics_dir = RESULTS_DIR / "metrics"
    metrics_dir.mkdir(parents=True, exist_ok=True)

    metrics_path = metrics_dir / f"metrics_{experiment_name}.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(test_metrics, f, indent=2, ensure_ascii=False)

    print(f"Model saved to:   {model_dir}")
    print(f"Metrics saved to: {metrics_path}")

    if push_to_hub_repo:
        api = HfApi()
        api.create_repo(repo_id=push_to_hub_repo, repo_type="model", private=True, exist_ok=True)
        trainer.model.push_to_hub(push_to_hub_repo, private=True,
                                  commit_message=f"Upload PhoBERT {experiment_name} model")
        tokenizer.push_to_hub(push_to_hub_repo, private=True,
                              commit_message="Upload PhoBERT tokenizer")
        api.upload_file(
            path_or_fileobj=str(metrics_path),
            path_in_repo="test_metrics.json",
            repo_id=push_to_hub_repo, repo_type="model",
        )
        print(f"Uploaded: https://huggingface.co/{push_to_hub_repo}")

    return trainer, test_metrics

In [ ]:
trainer, test_metrics = train_experiment(
    experiment_name="combined",
    model_dir_name="combined_phobert",
    tokenized=tokenized,
    push_to_hub_repo=f"{whoami()['name']}/vietnamese-hsd-phobert-combined",
)

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  543MB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B /  543MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.decoder.weight      | UNEXPECTED |
lm_head.decoder.bias        | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

[combined] test metrics: {'test_loss': 0.5512958765029907, 'test_accuracy': 0.7796532846715328, 'test_macro_f1': 0.5725161417163922, 'test_weighted_f1': 0.8074052686099449, 'test_hate_f1': 0.5798429319371727}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to:   /content/drive/MyDrive/Hate_Speech_Detection/models/combined_phobert
Metrics saved to: /content/drive/MyDrive/Hate_Speech_Detection/results/metrics/metrics_combined.json

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...xu6c4f6/model.safetensors:   0%|          |  569kB /  540MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Uploaded: https://huggingface.co/AnoraLee/vietnamese-hsd-phobert-combined