# PhoBERT -- Single-augmentation experiments (EDA / BT / LLM)

Train trên các subset đã phân từ sẵn trên Hugging Face Hub (`*_segmented`), đánh giá trên `tdtu_dev` / `tdtu_test` (đã đóng băng).

**Chạy trên Google Colab** -- cần mount Drive và có sẵn secret `HF_TOKEN`.

## Dependencies

In [1]:
!pip install -q transformers datasets huggingface_hub scikit-learn accelerate sentencepiece
!pip install -q -U datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 18.1 MB/s eta 0:00:00

In [2]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Warning: Enable GPU in Runtime > Change runtime type.")

Device: cuda
GPU: Tesla T4

In [3]:
from google.colab import userdata
from huggingface_hub import login, whoami, HfApi

hf_token = userdata.get("HF_TOKEN")
login(token=hf_token, add_to_git_credential=False)
user_info = whoami()
print(f"Authenticated as: {user_info['name']}")

Authenticated as: AnoraLee

In [4]:
from google.colab import drive
from pathlib import Path

drive.mount("/content/drive")

PROJECT_DIR = Path("/content/drive/MyDrive/Hate_Speech_Detection")
MODELS_DIR = PROJECT_DIR / "models"
RESULTS_DIR = PROJECT_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project root: {PROJECT_DIR}")

Mounted at /content/drive
Project root: /content/drive/MyDrive/Hate_Speech_Detection

In [5]:
MODEL_NAME = "vinai/phobert-base"
MAX_LENGTH = 128
SEED = 42
LABELS = ["CLEAN", "OFFENSIVE", "HATE"]

label2id = {label: index for index, label in enumerate(LABELS)}
id2label = {index: label for label, index in label2id.items()}

# Repo data trên Hugging Face Hub
HF_DATA_REPO = "AnoraLee/tdtu_vietnamese_hsd_final"

# Tên subset tương ứng cho từng thí nghiệm (đổi nếu repo Hub đặt tên khác)
SUBSET_EDA = "eda_segmented"
SUBSET_BT  = "bt_segmented"
SUBSET_LLM = "llm_segmented"
# Dev/test lấy từ bất kỳ subset nào (giống nhau giữa các split)
SUBSET_REF = "baseline_segmented"

## Load dev/test đã đóng băng từ Hugging Face Hub

In [6]:
from datasets import load_dataset

print(f"Load dev/test từ subset [{SUBSET_REF}]...")
ref_ds = load_dataset(HF_DATA_REPO, SUBSET_REF)
print(ref_ds)

dev_df = ref_ds["tdtu_dev"].to_pandas()
test_df = ref_ds["tdtu_test"].to_pandas()

dev_df  = dev_df.dropna(subset=["text", "label"]).reset_index(drop=True)
test_df = test_df.dropna(subset=["text", "label"]).reset_index(drop=True)

print(f"Validation: {dev_df.shape}")
print(f"Test:       {test_df.shape}")

Load dev/test từ subset [baseline_segmented]...

README.md:   0%|          | 0.00/1.76k [00:00<?, ?B/s]

baseline_segmented/tdtu_train-00000-of-0(…): reconstructing file:   0%|          |  0.00B / 8.69MB

baseline_segmented/tdtu_train-00000-of-0(…): downloading bytes:           |  0.00B

baseline_segmented/tdtu_dev-00000-of-000(…): reconstructing file:   0%|          |  0.00B /  127kB

baseline_segmented/tdtu_dev-00000-of-000(…): downloading bytes:           |  0.00B

baseline_segmented/tdtu_test-00000-of-00(…): reconstructing file:   0%|          |  0.00B /  314kB

baseline_segmented/tdtu_test-00000-of-00(…): downloading bytes:           |  0.00B

Generating tdtu_train split:   0%|          | 0/86719 [00:00<?, ? examples/s]

Generating tdtu_dev split:   0%|          | 0/2650 [00:00<?, ? examples/s]

Generating tdtu_test split:   0%|          | 0/6576 [00:00<?, ? examples/s]

DatasetDict({
    tdtu_train: Dataset({
        features: ['text', 'label'],
        num_rows: 86719
    })
    tdtu_dev: Dataset({
        features: ['text', 'label'],
        num_rows: 2650
    })
    tdtu_test: Dataset({
        features: ['text', 'label'],
        num_rows: 6576
    })
})
Validation: (2650, 2)
Test:       (6576, 2)

## Tokenizer + hàm dùng chung

In [7]:
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )

def prepare_split(df):
    output = df[["text", "label"]].dropna().copy()
    assert output["label"].isin(LABELS).all(), "Unexpected label found."
    output["label"] = output["label"].map(label2id)
    return Dataset.from_pandas(output, preserve_index=False)

def build_tokenized_dataset(train_df, dev_df, test_df):
    dataset = DatasetDict({
        "train": prepare_split(train_df),
        "validation": prepare_split(dev_df),
        "test": prepare_split(test_df),
    })
    tokenized = dataset.map(tokenize_function, batched=True)
    tokenized = tokenized.rename_column("label", "labels")
    model_columns = [
        c for c in ["input_ids", "attention_mask", "token_type_ids", "labels"]
        if c in tokenized["train"].column_names
    ]
    tokenized.set_format("torch", columns=model_columns)
    print(tokenized)
    return tokenized

config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.13M [00:00<?, ?B/s]

## Metrics

In [8]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    """Unified metric schema -- MUST stay identical across all 3 notebooks
    so results in the report are directly comparable."""
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro"),
        "weighted_f1": f1_score(labels, predictions, average="weighted"),
        "hate_f1": f1_score(labels, predictions, labels=[LABELS.index("HATE")], average="macro"),
    }

## Train (hàm dùng chung)

In [9]:
import json
from transformers import TrainingArguments, AutoModelForSequenceClassification, Trainer, set_seed, EarlyStoppingCallback

set_seed(SEED)

def train_experiment(experiment_name, model_dir_name, tokenized, push_to_hub_repo=None):
    """Load a FRESH PhoBERT model and train one experiment end to end.
    Always instantiates a new model -- never reuses a model/trainer object
    from a previous cell, to avoid accidental weight leakage between runs."""
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=3, label2id=label2id, id2label=id2label,
    )
    model_dir = MODELS_DIR / model_dir_name

    training_args = TrainingArguments(
        output_dir=str(model_dir / "_checkpoints"),
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=10,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        fp16=torch.cuda.is_available(),
        logging_steps=50,
        report_to="none",
        save_total_limit=1,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized["train"],
        eval_dataset=tokenized["validation"],
        processing_class=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    trainer.train()

    test_metrics = trainer.evaluate(tokenized["test"], metric_key_prefix="test")
    print(f"[{experiment_name}] test metrics: {test_metrics}")

    trainer.save_model(model_dir)
    tokenizer.save_pretrained(model_dir)

    metrics_dir = RESULTS_DIR / "metrics"
    metrics_dir.mkdir(parents=True, exist_ok=True)

    metrics_path = metrics_dir / f"metrics_{experiment_name}.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(test_metrics, f, indent=2, ensure_ascii=False)

    print(f"Model saved to:   {model_dir}")
    print(f"Metrics saved to: {metrics_path}")

    if push_to_hub_repo:
        api = HfApi()
        api.create_repo(repo_id=push_to_hub_repo, repo_type="model", private=True, exist_ok=True)
        trainer.model.push_to_hub(push_to_hub_repo, private=True,
                                  commit_message=f"Upload PhoBERT {experiment_name} model")
        tokenizer.push_to_hub(push_to_hub_repo, private=True,
                              commit_message="Upload PhoBERT tokenizer")
        api.upload_file(
            path_or_fileobj=str(metrics_path),
            path_in_repo="test_metrics.json",
            repo_id=push_to_hub_repo, repo_type="model",
        )
        print(f"Uploaded: https://huggingface.co/{push_to_hub_repo}")

    return trainer, test_metrics

## Hàm load subset từ Hub + chạy 1 thí nghiệm

In [10]:
def load_train_subset(subset_name):
    """Load 1 subset đã phân từ sẵn từ HF Hub và trả về train DataFrame."""
    print(f"  Load subset [{subset_name}]...")
    ds = load_dataset(HF_DATA_REPO, subset_name)
    df = ds["tdtu_train"].to_pandas()
    df = df.dropna(subset=["text", "label"]).reset_index(drop=True)
    print(f"  Train: {df.shape} -- {df['label'].value_counts().to_dict()}")
    return df

In [11]:
def run_single_augmentation_experiment(experiment_name, model_dir_name, subset_name, push=True):
    """Chạy 1 thí nghiệm single-augmentation: load subset từ Hub -> tokenize -> train."""
    train_df = load_train_subset(subset_name)
    tokenized = build_tokenized_dataset(train_df, dev_df, test_df)

    repo = f"{whoami()['name']}/vietnamese-hsd-phobert-{experiment_name}" if push else None
    return train_experiment(experiment_name, model_dir_name, tokenized, push_to_hub_repo=repo)

## Experiment 1 -- EDA

In [ ]:
eda_trainer, eda_metrics = run_single_augmentation_experiment(
    experiment_name="eda",
    model_dir_name="eda_phobert",
    subset_name=SUBSET_EDA,
)

## Experiment 2 -- Back-translation

In [12]:
bt_trainer, bt_metrics = run_single_augmentation_experiment(
    experiment_name="bt",
    model_dir_name="bt_phobert",
    subset_name=SUBSET_BT,
)

  Load subset [bt_segmented]...

README.md:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

bt_segmented/tdtu_train-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B /  857kB

bt_segmented/tdtu_train-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating tdtu_train split:   0%|          | 0/4946 [00:00<?, ? examples/s]

  Train: (4946, 4) -- {'OFFENSIVE': 3944, 'HATE': 1002}

Map:   0%|          | 0/4946 [00:00<?, ? examples/s]

Map:   0%|          | 0/2650 [00:00<?, ? examples/s]

Map:   0%|          | 0/6576 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 4946
    })
    validation: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 2650
    })
    test: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 6576
    })
})

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  543MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.decoder.weight      | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.decoder.bias        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors: reconstructing file:   0%|          |  0.00B /  543MB

model.safetensors: downloading bytes:           |  0.00B

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

[bt] test metrics: {'test_loss': 5.1758012771606445, 'test_accuracy': 0.09808394160583941, 'test_macro_f1': 0.18028775955247936, 'test_weighted_f1': 0.051727420456849735, 'test_hate_f1': 0.4271698113207547}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to:   /content/drive/MyDrive/Hate_Speech_Detection/models/bt_phobert
Metrics saved to: /content/drive/MyDrive/Hate_Speech_Detection/results/metrics/metrics_bt.json

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...fjesv55/model.safetensors:   0%|          |  554kB /  540MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Uploaded: https://huggingface.co/AnoraLee/vietnamese-hsd-phobert-bt

## Experiment 3 -- LLM-generated

In [ ]:
llm_trainer, llm_metrics = run_single_augmentation_experiment(
    experiment_name="llm",
    model_dir_name="llm_phobert",
    subset_name=SUBSET_LLM,
)